#!/bin/bash
if [[ "$1" == add* ]]; then
   /usr/bin/env python3 ~/.local/bin/pylib/add.py $2 $3
elif [[ "$1" == sub* ]]; then
   /usr/bin/env python3 ~/.local/bin/pylib/sub.py $2 $3
elif [[ "$1" == div* ]]; then
   /usr/bin/env python3 ~/.local/bin/pylib/div.py $2 $3
elif [[ "$1" == mul* ]]; then
   /usr/bin/env python3 ~/.local/bin/pylib/mult.py $2 $3
fi
