#!/bin/bash

if [ "$PYMATHMODE" == "DEV" ]; then
   if [ -d "/workspace/pymath" ]; then
      PYMATHLIB=/workspace/pymath
   else
      PYMATHLIB=/home/$USER/Documents/Python/pymath
   fi
else
   PYMATHLIB=/home/$USER/.local/bin/pymath
fi

HASH=$(cat "$PYMATHLIB/version.txt")

if [[ "$1" == add* ]]; then
   /usr/bin/env python3 $PYMATHLIB/pylib/cli.py $@
elif [[ "$1" == sub* ]]; then
   /usr/bin/env python3 $PYMATHLIB/pylib/cli.py $@
elif [[ "$1" == div* ]]; then
   /usr/bin/env python3 $PYMATHLIB/pylib/cli.py $@
elif [[ "$1" == mul* ]]; then
   /usr/bin/env python3 $PYMATHLIB/pylib/cli.py $@
elif [[ "$1" == sqr* ]]; then
   /usr/bin/env python3 $PYMATHLIB/pylib/cli.py $@
elif [[ "$1" == gui* ]]; then
   /usr/bin/env python3 $PYMATHLIB/app.py gui
else
   echo "Invalid operation"
   echo ""
   echo "Usage: pymath <OPERATION> [int1, int2, int3]"
   echo ""
   echo "   mult*: multiply"
   echo "   div*: divide"
   echo "   sub*: subtract"
   echo "   add*: addition"
   echo "   sqr*: square root"
   echo "   gui*: GUI interface"
   echo ""

   if [ "$HASH        HEAD" == "$(git ls-remote https://github.com/eggsnham07/pymath.git HEAD)" ]; then
      echo "There may be a newer version of pymath!"
      echo ""
      echo "$HASH        HEAD"
      echo "$(git ls-remote https://github.com/eggsnham07/pymath.git HEAD)"
   fi
fi
