#!/bin/bash
if [[ "$1" == add* ]]; then
   /usr/bin/env python3 ~/.local/bin/pylib/add.py $@
elif [[ "$1" == sub* ]]; then
   /usr/bin/env python3 ~/.local/bin/pylib/sub.py $@
elif [[ "$1" == div* ]]; then
   /usr/bin/env python3 ~/.local/bin/pylib/div.py $@
elif [[ "$1" == mul* ]]; then
   /usr/bin/env python3 ~/.local/bin/pylib/mult.py $@
elif [[ "$1" == sqr* ]]; then
   /usr/bin/env python3 ~/.local/bin/pylib/sqrt.py $@
fi
